import type { Application } from "./types";

function ts(date: string, time: string) {
  return `${date}T${time}:00Z`;
}

export const mockApplications: Application[] = [
  {
    id: "app_001",
    serviceId: "income_cert",
    serviceName: "Income Certificate",
    department: "Revenue Department",
    status: "processing",
    referenceNumber: "GOV/2024/001847",
    appliedDate: ts("2024-08-12", "10:30"),
    lastUpdated: ts("2024-08-15", "14:20"),
    estimatedCompletion: "2024-08-20",
    progress: 60,
    applicantName: "Rajesh Kumar",
    contactPhone: "9876543210",
    contactEmail: "rajesh@email.com",
    timeline: [
      { id: "tl_1_1", status: "draft", label: "Draft Created", description: "Application form started", timestamp: ts("2024-08-12", "10:30"), completed: true },
      { id: "tl_1_2", status: "submitted", label: "Application Submitted", description: "All documents uploaded", timestamp: ts("2024-08-12", "11:15"), completed: true },
      { id: "tl_1_3", status: "under_review", label: "Under Review", description: "Department reviewing application", timestamp: ts("2024-08-13", "09:00"), completed: true },
      { id: "tl_1_4", status: "processing", label: "Processing", description: "Application is being processed", timestamp: ts("2024-08-15", "14:20"), completed: false },
      { id: "tl_1_5", status: "completed", label: "Completed", description: "Certificate will be issued", timestamp: "", completed: false },
    ],
    documents: [
      { id: "doc_1", name: "Aadhaar Card", status: "verified", uploadedAt: "2024-08-12" },
      { id: "doc_2", name: "Salary Slip", status: "verified", uploadedAt: "2024-08-12" },
      { id: "doc_3", name: "Bank Statement", status: "uploaded", uploadedAt: "2024-08-12" },
    ],
  },
  {
    id: "app_002",
    serviceId: "aadhaar_update",
    serviceName: "Aadhaar Update",
    department: "UIDAI",
    status: "approved",
    referenceNumber: "GOV/2024/001654",
    appliedDate: ts("2024-08-05", "09:15"),
    lastUpdated: ts("2024-08-10", "16:45"),
    completedDate: "2024-08-10",
    progress: 100,
    applicantName: "Rajesh Kumar",
    contactPhone: "9876543210",
    timeline: [
      { id: "tl_2_1", status: "draft", label: "Draft Created", timestamp: ts("2024-08-05", "09:15"), completed: true },
      { id: "tl_2_2", status: "submitted", label: "Application Submitted", timestamp: ts("2024-08-05", "09:30"), completed: true },
      { id: "tl_2_3", status: "under_review", label: "Under Review", timestamp: ts("2024-08-06", "10:00"), completed: true },
      { id: "tl_2_4", status: "processing", label: "Processing", timestamp: ts("2024-08-08", "11:30"), completed: true },
      { id: "tl_2_5", status: "completed", label: "Completed", description: "Aadhaar updated successfully", timestamp: ts("2024-08-10", "16:45"), completed: true },
    ],
    documents: [
      { id: "doc_4", name: "Current Aadhaar", status: "verified", uploadedAt: "2024-08-05" },
      { id: "doc_5", name: "Address Proof", status: "verified", uploadedAt: "2024-08-05" },
    ],
  },
  {
    id: "app_003",
    serviceId: "driving_license",
    serviceName: "Driving License (Renewal)",
    department: "Transport Department",
    status: "submitted",
    referenceNumber: "GOV/2024/001923",
    appliedDate: ts("2024-08-18", "14:00"),
    lastUpdated: ts("2024-08-18", "14:00"),
    estimatedCompletion: "2024-09-05",
    progress: 20,
    applicantName: "Rajesh Kumar",
    contactPhone: "9876543210",
    timeline: [
      { id: "tl_3_1", status: "draft", label: "Draft Created", timestamp: ts("2024-08-18", "13:45"), completed: true },
      { id: "tl_3_2", status: "submitted", label: "Application Submitted", description: "Awaiting department review", timestamp: ts("2024-08-18", "14:00"), completed: false },
      { id: "tl_3_3", status: "under_review", label: "Under Review", timestamp: "", completed: false },
      { id: "tl_3_4", status: "processing", label: "Processing", timestamp: "", completed: false },
      { id: "tl_3_5", status: "completed", label: "Completed", timestamp: "", completed: false },
    ],
    documents: [
      { id: "doc_6", name: "Current License", status: "verified", uploadedAt: "2024-08-18" },
      { id: "doc_7", name: "Medical Certificate", status: "uploaded", uploadedAt: "2024-08-18" },
      { id: "doc_8", name: "Passport Photo", status: "verified", uploadedAt: "2024-08-18" },
    ],
  },
  {
    id: "app_004",
    serviceId: "birth_cert",
    serviceName: "Birth Certificate",
    department: "Civil Registration",
    status: "rejected",
    referenceNumber: "GOV/2024/001456",
    appliedDate: ts("2024-08-01", "11:00"),
    lastUpdated: ts("2024-08-08", "10:30"),
    rejectionReason: "Hospital record not clearly visible. Please re-upload with all corners visible.",
    progress: 0,
    applicantName: "Rajesh Kumar",
    contactPhone: "9876543210",
    timeline: [
      { id: "tl_4_1", status: "draft", label: "Draft Created", timestamp: ts("2024-08-01", "11:00"), completed: true },
      { id: "tl_4_2", status: "submitted", label: "Application Submitted", timestamp: ts("2024-08-01", "11:30"), completed: true },
      { id: "tl_4_3", status: "under_review", label: "Under Review", timestamp: ts("2024-08-03", "09:00"), completed: true },
      { id: "tl_4_4", status: "rejected", label: "Rejected", description: "Hospital record not clearly visible", timestamp: ts("2024-08-08", "10:30"), completed: true },
    ],
    documents: [
      { id: "doc_9", name: "Hospital Record", status: "rejected", uploadedAt: "2024-08-01" },
      { id: "doc_10", name: "Parents Aadhaar", status: "verified", uploadedAt: "2024-08-01" },
      { id: "doc_11", name: "Address Proof", status: "verified", uploadedAt: "2024-08-01" },
    ],
  },
  {
    id: "app_005",
    serviceId: "property_tax",
    serviceName: "Property Tax Payment",
    department: "Municipal Corporation",
    status: "approved",
    referenceNumber: "GOV/2024/001200",
    appliedDate: ts("2024-07-28", "16:00"),
    lastUpdated: ts("2024-07-28", "16:05"),
    completedDate: "2024-07-28",
    progress: 100,
    applicantName: "Rajesh Kumar",
    contactPhone: "9876543210",
    timeline: [
      { id: "tl_5_1", status: "draft", label: "Draft Created", timestamp: ts("2024-07-28", "16:00"), completed: true },
      { id: "tl_5_2", status: "submitted", label: "Payment Submitted", timestamp: ts("2024-07-28", "16:02"), completed: true },
      { id: "tl_5_3", status: "completed", label: "Payment Confirmed", description: "Receipt generated", timestamp: ts("2024-07-28", "16:05"), completed: true },
    ],
    documents: [
      { id: "doc_12", name: "Property Document", status: "verified", uploadedAt: "2024-07-28" },
    ],
  },
  {
    id: "app_006",
    serviceId: "caste_cert",
    serviceName: "Caste Certificate",
    department: "Revenue Department",
    status: "draft",
    referenceNumber: "GOV/2024/002100",
    appliedDate: ts("2024-08-20", "09:00"),
    lastUpdated: ts("2024-08-20", "09:00"),
    progress: 10,
    applicantName: "Rajesh Kumar",
    contactPhone: "9876543210",
    timeline: [
      { id: "tl_6_1", status: "draft", label: "Draft Created", description: "Form partially filled", timestamp: ts("2024-08-20", "09:00"), completed: false },
      { id: "tl_6_2", status: "submitted", label: "Application Submitted", timestamp: "", completed: false },
      { id: "tl_6_3", status: "under_review", label: "Under Review", timestamp: "", completed: false },
      { id: "tl_6_4", status: "processing", label: "Processing", timestamp: "", completed: false },
      { id: "tl_6_5", status: "completed", label: "Completed", timestamp: "", completed: false },
    ],
    documents: [
      { id: "doc_13", name: "Aadhaar Card", status: "verified", uploadedAt: "2024-08-20" },
      { id: "doc_14", name: "Caste Proof", status: "required" as "uploaded" | "verified" | "rejected" },
    ],
  },
];
